config/routes.rb
Rails.application.routes.draw do
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  root 'static_pages#home'
  resources :users do
    get :search, on: :collection
    post :search, on: :collection
    resources :friendships, only: %i[create] 
  end
  resources :groups, only: %i[index new create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :user_groups, dependent: :destroy
  has_many :users, through: :user_groups

  validates :name, presence: true
  validates :description, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_groups, dependent: :destroy
  has_many :groups, through: :user_groups
  
  has_many :active_friendship, class_name: "Friendship", foreign_key: "follower_id", dependent: :destroy
  has_many :passive_friendship, class_name: "Friendship", foreign_key: "followed_id", dependent: :destroy
  has_many :following, through: :active_friendship, source: :followed
  has_many :followers, through: :passive_friendship, source: :follower

  validates :name, presence: true, length: { maximum: 20 }
  validates :email, presence: true, uniqueness: true, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }

  has_secure_password
  # TODO: passwordのvalidationエラーを解決
  # validates :password, presence: true, length: { minimum: 6 }

  def follow(other_user)
    active_friendship.create(followed_id: other_user.id)
  end

  def following?(other_user)
    active_friendship.find_by(followed_id: other_user.id)
  end

  def follow_requests
    follow_request_users = []
    followers.each do |follower|
      if !following?(follower)
        follow_request_users.push(follower)
      end
    end
    return follow_request_users
  end

  def matchers
    following & followers
  end
end

app/models/user_group.rb
class UserGroup < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper

  private
  
    def logged_in_user
      if !logged_in?
        redirect_to login_url
      end
    end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  def create
    user = User.find(params[:user_id])
    if current_user.follow(user)
      redirect_to users_url
    else
      redirect_to search_users_path
    end
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :logged_in_user, only: [:index, :new]

  def index
    @groups = current_user.groups
  end

  def new
    @group = Group.new
  end

  def create

    @group = Group.new(group_params)

    if @group.save
      redirect_to groups_path
    else
      render :new
    end
  end

  private

    def group_params
      params.require(:group).permit(:name, :description, user_ids: [])
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to users_path
    else
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index]

  def index
    @current_user = current_user
    @follow_request_users = current_user.follow_requests
    @friends = @current_user.matchers
  end

  def new
    @user = User.new
  end

  def create
    user = User.new(user_params)
    if user.save
      log_in user
      redirect_to users_url
    else
      @user = User.new
      render 'new'
    end
  end

  def search
    if defined?(params[:search_param][:email]) && params[:search_param][:email].present?
      searched_user = User.find_by(email: params[:search_param][:email])
       if searched_user != current_user && !current_user.following.find {|u| u==searched_user}
        @searched_user = searched_user
       end
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/views/groups/index.html.haml
%table
  - @groups.each do |g|
    %tbody
      %tr
        = g.name

app/views/groups/new.html.haml
.container.mx-auto
  %h1.text-4xl グループ作成
  = form_with model: @group do |f|
    %div
      = f.label :name, class: 'block'
      = f.text_field :name, class: 'form-input w-full'
    %div
      = f.label :description, class: 'block'
      = f.text_area :description, class: 'w-full'
    %div
      = f.label :user_ids, class: 'block'
      = f.select :user_ids, User.pluck(:name, :id), {}, { multiple: true, class: 'form-multiselect w-full' }
    = f.submit '送信', class: 'bg-blue-500 py-2 px-4 text-white rounded'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title LineClone
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_pack_tag 'application'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/static_pages/home.html.haml
%div
  .text-center.pt-40.pb-40
    %h1.text-2xl LINE_clone_appへようこそ
  .text-center.h-18.py-6
    = link_to 'ログイン', login_path, class: 'bg-green-500 text-white rounded font-semibold py-4 px-40'
  .text-center.h-18.py-6
    = link_to '新規登録', new_user_path, class: 'border rounded font-semibold py-4 px-40'
  .text-center.h-18.py-6
    = link_to 'グループ作成', new_group_path, class: 'bg-blue-500 text-white rounded font-semibold py-4 px-40'
  .text-center.h-18.py-6
    = link_to 'グループ一覧', groups_path, class: 'bg-blue-500 text-white rounded font-semibold py-4 px-40'

app/views/users/index.html.haml
%div
  .text-center.pt-40.pb-32
    %h1.text-2xl ユーザー一覧
  .ml-auto.mr-auto{:class => "w-[400px]"}
    %p 自分
    .border.pl-4
      = @current_user.name
    - if @follow_request_users.present?
      %p 友達リクエスト
      - @follow_request_users.each do |follow_request_user|
        .border.pl-4
          .inline-block.mr-auto{:class => 'w-[329px]'}
            = follow_request_user.name
          .inline-block.px-2.text-right.bg-gray-200.rounded
            = link_to '追加', user_friendships_path(user_id: follow_request_user.id), method: :post
    - if @friends.present?
      %p 友達
      - @friends.each do |friend|
        .border.pl-4
          = friend.name
    .text-center.h-18.py-6
      = link_to '友達追加', search_users_path, class: 'bg-blue-500 text-white rounded bg-blue-500 rounded py-2 px-20'
  - if logged_in?
    = link_to 'ログアウト', logout_path, method: :delete

app/views/users/new.html.haml
%div
  .text-center.pt-40.pb-20
    %h1.text-2xl ユーザー新規作成
  .border-2.text-center.py-4.ml-auto.mr-auto{:class => 'w-[400px]'}
    = form_with model: @user do |f|
      .py-4
        = f.label :name, '名前', class: 'inline-block text-left w-[150px]'
        = f.text_field :name, class: 'border'
      .py-4
        = f.label :email, class: 'inline-block text-left w-[150px]'
        = f.email_field :email, class: 'border'
      .py-4
        = f.label :password, 'パスワード', class: 'inline-block text-left w-[150px]'
        = f.password_field :password, class: 'border'
      .py-4
        = f.label :password_confirmation, 'パスワード(再入力)', class: 'inline-block text-left w-[150px]'
        = f.password_field :password_confirmation, class: 'border'
      .py-4
        = f.submit '送信', class: 'font-semibold px-20 rounded'

app/views/users/search.html.haml
%div
  .text-center.pt-40.pb-32
    %h1.text-2xl 友達追加
  .border-2.text-center.py-4.ml-auto.mr-auto{:class => 'w-[400px]'}
    = form_with scope: :search_param, url: search_users_path do |f|
      .py-4
        = f.label :email, class: 'inline-block text-left w-[150px]'
        = f.email_field :email, class: 'border'
      .py-4 
        = f.submit '検索', class: 'bg-green-500 text-white px-20 rounded'
    - if @searched_user.present?
      .border.pl-4
        .inline-block.mr-auto{:class => 'w-[320px]'}
          = @searched_user.name
        .inline-block.px-2.text-right.bg-gray-200.rounded
          = link_to '追加', user_friendships_path(user_id: @searched_user.id), method: :post